version: "3"

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=confession_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=andrew
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=confession_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andrew
    volumes:   ## keep it for persisting data after docker-compose down
      - postgres-db:/var/lib/postgresql/data


    
volumes:
  postgres-db:
