version: "3"

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=confession_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=andrew
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=confession_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andrew
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
