# Generated by Django 5.2.3 on 2025-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confessions", "0002_warnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField()),
            ],
        ),
    ]
